	.align 2
gText_ConfirmSave::
	.string "¿Quieres guardar la partida?$"

gText_AlreadySavedFile::
	.string "Ya tienes una partida guardada.\n"
	.string "¿Quieres sobreescribirla?$"

gText_SavingDontTurnOff::
	.string "Guardando…\n"
	.string "No apagues la consola.$"

gText_PlayerSavedGame::
	.string "{PLAYER} guardó la partida.$"

gText_DifferentSaveFile::
	.string "Ya tienes una partida guardada\n"
	.string "¿Quieres sobreescribirla?.$"

gText_SaveError::
	.string "Save error.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "Guardando…\n"
	.string "No apagues la consola.$"
